[32mINFO[39m:     Started server process [[36m14184[39m]
[32mINFO[39m:     Waiting for application startup.
[32mINFO[39m:     Application startup complete.
[32mINFO[39m:     127.0.0.1:59256 - "[1mPOST /prediction HTTP/1.1[22m" [91m500 Internal Server Error
[31mERROR[39m:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/./api/main.py", line 73, in heart_prediciton
    loaded_model = joblib.load(artifact)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/home/diego/.pyenv/versions/3.10.2/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/home/diego/.pyenv/versions/3.10.2/lib/python3.10/pickle.py", line 1538, in load_stack_global
    self.append(self.find_class(module, name))
  File "/home/diego/.pyenv/versions/3.10.2/lib/python3.10/pickle.py", line 1580, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'train'
[32mINFO[39m:     Shutting down
[32mINFO[39m:     Waiting for application shutdown.
[32mINFO[39m:     Application shutdown complete.
