[32mINFO[39m:     Started server process [[36m12314[39m]
[32mINFO[39m:     Waiting for application startup.
[32mINFO[39m:     Application startup complete.
[32mINFO[39m:     127.0.0.1:59054 - "[1mPOST /prediction HTTP/1.1[22m" [91m500 Internal Server Error
[31mERROR[39m:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/./main.py", line 75, in heart_prediciton
    prediction = loaded_model.predict(X)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/./train.py", line 50, in predict
    return self.model_pipeline.predict(X)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 457, in predict
    Xt = transform.transform(Xt)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/./preprocessing.py", line 327, in transform
    X = pd.DataFrame(pipeline_preprocessing.transform(X), columns=colnames)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 1204, in transform
    Xs = Parallel(n_jobs=self.n_jobs)(
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/sklearn/utils/fixes.py", line 117, in __call__
    return self.function(*args, **kwargs)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 853, in _transform_one
    res = transformer.transform(X)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 635, in transform
    Xt = transform.transform(Xt)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/./preprocessing.py", line 127, in transform
    return X.loc[:, self.numerical_features]
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 1149, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 827, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 1191, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 1132, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexing.py", line 1327, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/diego/machine learning/machineLearnig_project1/machine-learning-project-of-heart-api/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5842, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'], dtype='object')] are in the [columns]"
[32mINFO[39m:     Shutting down
[32mINFO[39m:     Waiting for application shutdown.
[32mINFO[39m:     Application shutdown complete.
